### ISSUE TITLE
Long press on Pokeball does not function properly

### ISSUE THREAD

**Issue by ChiIIerr** [benjy3gg/pokeRadar#1]
Instead of the pokeball at the top left being long-click to reopen, it is everywhere on the top half of the screen.

**Comment by benjy3gg** [comment]
try to longclick on the mapsview and it should "transform" into the pokeball!

**Comment by ChiIIerr** [comment]
Oh, it transforms, it simply has the touch area still enabled for the top half even after it transforms.

**Comment by ChiIIerr** [comment]
Here's a video of what I'm talking about. Please ignore the last part where I try desperately to figure out how to end the video :P 

Please notice where I'm tapping and what happens/doesn't happen when I tap.

https://www.youtube.com/watch?v=2ijGzV_Nq7s

**Comment by benjy3gg** [comment]
This should be fixed in the current version!
