### ISSUE TITLE
Search area shows extremely wide.

### ISSUE THREAD

**Issue by DragnHntr** [benjy3gg/pokeRadar#10]
The horizontal search area shows extremely wide. In the attached screenshot you can see that even with the horizontal distance minimized, it still extends 5 times as wide as it is tall. I think this is affecting the search algorithm as well, as it only ever shows pokemon in a narrow vertical strip on my current location.

![screenshot_20160723-191309](https://cloud.githubusercontent.com/assets/3485636/17080957/ee08ad96-5109-11e6-9b3f-7e8ed8dc2ada.png)

**Comment by benjy3gg** [comment]
do you know how big the area thats showing is approximatly?

**Comment by DragnHntr** [comment]
When both sliders are set to minimum, the height is a couple hundred feet, and the width is like 3.5 miles.

**Comment by DragnHntr** [comment]
This is solved in the new version with the search area being a circle instead of a square
