### ISSUE TITLE
[Bug] App won't close

### ISSUE THREAD

**Issue by ser86** [benjy3gg/pokeRadar#18]
If you have the overlay open and you swipe the pokeball to the bin icon the pokeball disappear but the map remain open.

![screenshot_20160725-110627](https://cloud.githubusercontent.com/assets/1152900/17096140/44924182-5258-11e6-9858-035fec86a0f7.png)
![screenshot_20160725-110633](https://cloud.githubusercontent.com/assets/1152900/17096141/44af93c2-5258-11e6-9b07-c413a7499a95.png)

Then, also with the map closed, if you kill the application via recent apps after a random time appear an application error.

![screenshot_20160725-115503_1](https://cloud.githubusercontent.com/assets/1152900/17097675/0cace676-525f-11e6-91fc-77dae6527949.jpg)

If you don't wait until the error appear and you reopen the app, the map and the pokeball doesn't became visible

![screenshot_20160725-111207](https://cloud.githubusercontent.com/assets/1152900/17096275/d293a818-5258-11e6-99bd-47fa0da752fc.png)

**Comment by benjy3gg** [comment]
yeah i know of the bug..
will fix it this evening.  In the meantime just close the app by closing it through recent apps.
thanks for the detailed images.
