### ISSUE TITLE
[Improvement] Position via Wi-Fi

### ISSUE THREAD

**Issue by ser86** [benjy3gg/pokeRadar#19]
As I see, the app correctly find the position if you are under a Wi-Fi network but the scanner won't start until GPS is active.
Is possible to improve it so isn't required to activate GPS just to fix initial position?

**Comment by benjy3gg** [comment]
i will try in the next version

**Comment by entsyymi** [comment]
This would be awesome. As of now, I have to go outside to get the scanner working, since my phone won't find a gps signal inside my house.
