### ISSUE TITLE
Won't work... says you are logged in and then crashes

### ISSUE THREAD

**Issue by klemax** [benjy3gg/pokeRadar#22]
Samsung Galaxy Core Prime, Android 5.1.1. Last working version was 0.2 which still works, but I had no luck with any of the newer versions :/.

The app is otherwise awsome and thank you for all the hard work!

**Comment by benjy3gg** [comment]
can you try to manually uninstall the current version and then install the new one!
https://github.com/benjy3gg/pokeRadar/releases/download/relase-v1.01/pokeRadar-1.01.apk

**Comment by klemax** [comment]
I've done that about 5 times now... still doesn't work. The second it says "You are logged in" it crashes.

**Comment by benjy3gg** [comment]
should be fixed in the playstore update 1.1!
