### ISSUE TITLE
App minimizes but no action after login

### ISSUE THREAD

**Issue by DGTnt** [benjy3gg/pokeRadar#23]
After login in with v1.01 the app minimizes but no further action afterwards like the overlay nor button

On Galaxy A3 2016 with android 5.11

**Comment by benjy3gg** [comment]
just close the app via the recents menu and start and login again.
Its a known bug

**Comment by DGTnt** [comment]
After a few attempts it remained sdoin this, even after a forced closure and restart of device. I rolled back to 0.3 untill solved

**Comment by DGTnt** [comment]
![screenshot_2016-07-25-13-25-29](https://cloud.githubusercontent.com/assets/7373552/17099920/942811be-526b-11e6-8da6-29e46283eb2a.png)
![screenshot_2016-07-25-13-25-09](https://cloud.githubusercontent.com/assets/7373552/17099923/990f12f4-526b-11e6-8d82-1de2cbe3f6e9.png)
![screenshot_2016-07-25-13-24-40](https://cloud.githubusercontent.com/assets/7373552/17099926/9ed50626-526b-11e6-822c-d7d5e552c040.png)

Perhaps the next shots of the logs might help ;). Doesn't look like normal bugs to me

**Comment by DGTnt** [comment]
Hi, here's an update for 1.02 by the Play Store.
Still same issue but even after a error Login it crashed.
I'll be attaching the Logfile from Install untill the few crashes, hopefully they help
[benjy3gg_Log_2016-07-25_17-37-23.txt](https://github.com/benjy3gg/pokeRadar/files/381879/benjy3gg_Log_2016-07-25_17-37-23.txt)

**Comment by benjy3gg** [comment]
yeah i found another bug. basically the app detected the failed login and still send the message to start the floating pokeball. That may be the bug!

I already uploaded v1.1 to app store!

**Comment by benjy3gg** [comment]
can you come to my discord real quick?
https://discord.gg/v3BPh

**Comment by benjy3gg** [comment]
fixed with 1.1
