### ISSUE TITLE
[BUG] Version 1.4 - White screen at start and crash

### ISSUE THREAD

**Issue by egoadk** [benjy3gg/pokeRadar#36]
Xiaomi Redmi Note 3 Pro with Android 5.1.1. I made sure I have GPS enabled and overlay pop up allowed.

My History:

0.2 worked fine
0.3 buggy and crashes a lot
0.31 crash on startup
1.01 crash after login
1.2 cannot even log, crash on app startup
1.3 crash to home after login
1.4 cannot even get login screen. White screen and crash.

**Comment by ser86** [comment]
Do you have tried to uninstall completely the app and then reinstall it?
It seems to be a problem of updating the early releases instead of uninstall and install the new one. I've experiment the same issues after doing this...

**Comment by egoadk** [comment]
Yup always did that. Completely uninstall.

**Comment by egoadk** [comment]
I just got info that it is a specific problem with Xiaomi phones.
