### ISSUE TITLE
Drag minimized pokeball

### ISSUE THREAD

**Issue by niayh** [benjy3gg/pokeRadar#4]
Love the app and works rather well straight out of the box for me.

I just thought I'd mention that when it comes to bubbles, there is no perfect place to put it on the screen. As such, it would be great if we could drag the minimized pokeball to a location of our choosing like facebook chat heads and such so that if the ball happens to obscure a button or block of text that we can move it out of the way.

Also, as I don't see any easy method of closing the app, so you could even drag it to the bottom middle to "delete" or close the app.

Thanks for all your awesome work!

**Comment by benjy3gg** [comment]
done
