### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by voidpublic** [benjy3gg/pokeRadar#44]
I get the notification, but it does not vibrate. or make a sound v2.42

**Comment by benjy3gg** [comment]
did you enable the sound/vibration in the menu?

**Comment by benjy3gg** [comment]
press the three dots and there should be two checkboxes

**Comment by voidpublic** [comment]
@benjy3gg  yep they are enabled, using a OPO with Cyanogen 12.1.1 (Android 5.1.1)

**Comment by benjy3gg** [comment]
hmm strange
will look into it later

**Comment by voidpublic** [comment]
@benjy3gg  just tried with v2.6, works like a charm. 

Thanks

Closed
