### ISSUE TITLE
No pokemon showing up on radar

### ISSUE THREAD

**Issue by mquinlan5502** [benjy3gg/pokeRadar#46]
Left the app opem for about 30 minutes and nothing is showing up on my radar.  My nearby menu has quite a few showing up right now. Version 2.6

**Comment by benjy3gg** [comment]
yeah, niantic changed the api.
Will update as soon as a fix is available!

**Comment by mquinlan5502** [comment]
Oh okay cool! Thanks for the info :)

**Comment by radicalero** [comment]
Hi! Yeah. Looking for it. 
For me, stoped working 2 days ago.
Nice work with the development of the app.
Best Regards!

**Comment by mquinlan5502** [comment]
Thanks so much for updating! This is the best tool out there

**Comment by mquinlan5502** [comment]
I think Niantic broke it again

**Comment by benjy3gg** [comment]
i need a little more information!
its still working for me!
what version are you on?

**Comment by mquinlan5502** [comment]
Oh! That is weird. Its the same issue, on version 3.3. Maybe there is literally nothing in my area ha ha. Left it running for about 20 mins. 

Thanks for the fast response!

**Comment by benjy3gg** [comment]
can you come to the discord channel pls?
https://discord.gg/pA6HK
