### ISSUE TITLE
Pokemon does not appear on the radar

### ISSUE THREAD

**Issue by matyyys** [benjy3gg/pokeRadar#47]
for about 1 day Pokemon is not already visible on the android.
Will there be an update on android, which fix it?

**Comment by radicalero** [comment]
The dev says it working on a new update to fix it.
I am looking for it too =)

**Comment by matyyys** [comment]
When will be update for android?

**Comment by ghost** [comment]
@Matyyys The API needs to be completely reverse engineered and there's no saying when it will be.
