### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by Kcirbuk** [benjy3gg/pokeRadar#54]
Hi, 

first of all thanks for your application, it's a great one. 
unfortunatly i am unable to use it since the version 2.5. 
i uninstalled it and reinstalled newer version (3.3 3.0) but when i launch the app and log in the application automatically shutdown itself and my phone show : 

Live Map Go has stop working

i am on Asus zenfone 2 and using a PTC account. the phone has not been rooted.
the issue occurs when i am using wifi or data.the processor on Zenfone 2 is an Intel Atom, it might have something to do with this. 

hope it can be fixed , i can provide further informations if you need it. 

Thanks!

**Comment by benjy3gg** [comment]
Hi. It would be nice if you could send me a logcat of when the app crashes. Search for "alogcat" on google ppay store

**Comment by benjy3gg** [comment]
this should be fixed
