### ISSUE TITLE
App crashing while opening

### ISSUE THREAD

**Issue by mucahidkambur** [benjy3gg/pokeRadar#8]
When i try to open app, it crashing and say application has stopped.

Sony Z2 D6503 ANDROID 6.0.1

**Comment by CJBok** [comment]
Same happens on the Nox Android Emulator version 3.7.0

**Comment by benjy3gg** [comment]
should be fixed. pls retry with v0.31

**Comment by benjy3gg** [comment]
fixed in 1.1
